# Generated by Django 5.1.3 on 2024-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnortLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('type', models.CharField(choices=[(1, 'Http'), (2, 'Icmp'), (3, 'Dns'), (4, 'Sql Injection')], max_length=20)),
                ('ip', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
