# Generated by Django 5.1.3 on 2024-11-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snort', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snortlog',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='snortlog',
            name='type',
            field=models.CharField(choices=[(1, 'HTTP'), (2, 'ICMP'), (3, 'DNS'), (4, 'SQL_INJECTION')], max_length=20),
        ),
    ]
