# Generated by Django 5.1.3 on 2024-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snort', '0002_rename_timestamp_snortlog_date_alter_snortlog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snortlog',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
